---
name: Screenshot
on:
  push:
  pull_request:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  screenshot:
    name: Screenshot
    permissions:
      contents: write
    # runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Screenshot PenAndPaperFloorplanner content
        uses: lowlighter/metrics@latest
        with:
          filename: images/screenshot.${{ matrix.os }}.svg
          token: NOT_NEEDED
          base: ""
          plugin_screenshot: yes
          plugin_screenshot_title: PenAndPaperFloorplanner-${{ matrix.os }}
          plugin_screenshot_url: https://karldaeubel.github.io/PenAndPaperFloorplanner
          plugin_screenshot_selector: "#content"
          # plugin_screenshot_viewport: {
          #   "width": 1280,
          #   "height": 1280
          # }
          # plugin_screenshot_wait: 2000
          # plugin_screenshot_background: yes
